---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.servicename}}"
  labels:
    app: "{{.Values.servicename}}"
    version: "{{.Values.version}}"
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: "{{.Values.servicename}}"
  template:
    metadata:
      labels:
        app: "{{.Values.servicename}}"
        version: "{{.Values.version}}"
    spec:
      containers:
      - name: "{{.Values.servicename}}"
        image: "{{.Values.imagepath}}:{{.Values.version}}"
        resources:
          requests:
            cpu: "{{.Values.cpurequest}}"
            memory: "{{.Values.memrequest}}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{.Values.port}}
---