---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.servicename}}"
  labels:
    app: "{{.Values.servicename}}"
    service: "{{.Values.servicename}}"
spec:
  ports:
  - port: {{.Values.port}}
    name: http
  selector:
    app: "{{.Values.servicename}}"
---