apiVersion: v1
data:
  tls.crt: {{.Values.tlscrt | b64enc }}
  tls.key: {{.Values.tlskey | b64enc }}
kind: Secret
metadata:
  name: "{{.Values.name}}"
  namespace: "{{.Values.namespace}}"
type: kubernetes.io/tls