---
- hosts: localhost
  ignore_unreachable: true
  ignore_errors: True
  vars:
      resource_group: <+serviceVariables.azureresourcegroup>
      location: '<+serviceVariables.azurelocation>'
      sbnamespace: <+serviceVariables.servicebusnamespace>
      topic: <+serviceVariables.servicebustopic>
      subscription: <+serviceVariables.servicebussubscription>
      returndatadirectory: <+pipeline.executionId>
      sku: <+serviceVariables.sku>
  tasks:
    - name: Ensure resource group exist
      tags: createresourcegroup
      block:
       - name: Check for resource group
         azure_rm_resourcegroup:
           name: "{{ resource_group }}"
           location: "{{ location }}"
         register: resourcegroupreturndata
      always:
       - name: Copy return data to file
         local_action:
          module: copy
          content: "{{ resourcegroupreturndata }}"
          dest: "/tmp/{{ pipelineexecutionid }}-resourcegroupreturndata"
    - name: Create a namespace
      tags: createnamespace
      block:
       - name: Create a namespace
         azure_rm_servicebus:
           name: "{{ sbnamespace }}"
           sku: "{{ sku }}"
           resource_group: "{{ resource_group }}"
         register: sbnamespacereturndata
      always:
       - name: Copy return data to file
         local_action:
          module: copy
          content: "{{ sbnamespacereturndata }}"
          dest: "/tmp/{{ pipelineexecutionid }}-sbnamespacereturndata"
    - name: Create a topic
      tags: createtopic
      block:
       - name: Create a topic
         azure_rm_servicebustopic:
           name: "{{ topic }}"
           namespace: "{{ sbnamespace }}"
           resource_group: "{{ resource_group }}"
         register: topicreturndata
      always:
       - name: Copy return data to file
         local_action:
          module: copy
          content: "{{ topicreturndata }}"
          dest: "/tmp/{{ pipelineexecutionid }}-topicreturndata"
    - name: Create a subscription
      tags: createsubscription
      block:
       - name: Create a subscription
         azure_rm_servicebustopicsubscription:
           name: "{{ subscription }}"
           topic: "{{ topic }}"
           namespace: "{{ sbnamespace }}"
           resource_group: "{{ resource_group }}"
         register: subscriptionreturndata
      always:
       - name: Copy return data to file
         local_action:
          module: copy
          content: "{{ subscriptionreturndata }}"
          dest: "/tmp/{{ pipelineexecutionid }}-subscriptionreturndata"